### ISSUE TITLE
Adding nav bar on site , 

### ISSUE THREAD

**Issue by Yuvraj-Parade** [Luciferlocas/nomen#33]
in that all resume's get categorize by the domain like frontend developer , then all frontend

https://github.com/user-attachments/assets/fa400caf-6249-48cc-9e2a-dfb341463678

 developer resume will shown

**Comment by Yuvraj-Parade** [comment]
also the logo of N , we can put on Top left corner

**Comment by Luciferlocas** [comment]
We want a very simple and sleek UI, adding a navigation will not be suitable for that. Instead of that on the card page a dropdown menu can be implemented in which different domains can be listed and the user can filter specific domains card they want to see.
