### ISSUE TITLE
bug: Inconsistent card sizes due to varying quote lengths

### ISSUE THREAD

**Issue by Luciferlocas** [Luciferlocas/nomen#34]
**Description:**

On the page where cards are displayed, the size of the cards changes depending on the length of the quotes. This inconsistency affects the overall layout, causing misalignment and a suboptimal user experience.

**Steps to Reproduce:**

Go to the page with the cards.
Observe that cards with longer quotes expand, while those with shorter quotes remain smaller.
Expected Behavior: All cards should maintain a consistent size regardless of the content inside them, improving visual alignment.

**Suggestions**

 One way to resolve this could be setting a min width for the card, you can refer to the [Tailwind](https://tailwindcss.com/docs/min-width#setting-the-minimum-width) documentation for help.

**Comment by Yuvraj-Parade** [comment]
i want to contribute on this issue

**Comment by Luciferlocas** [comment]
Go ahead @Yuvraj-Parade
