### ISSUE TITLE
Missing Back Button on Resume Page

### ISSUE THREAD

**Issue by piyush-gangrade** [Luciferlocas/nomen#39]
Description:
When viewing a specific resume, no back button is available to return to the /resume page. This affects user navigation, as they have to manually navigate back or refresh the page to view the list of resumes again.

Expected Behavior:
A back button should be available on the resume view page to allow users to return to the previous page (/resume).

![Screenshot 2024-10-10 004601](https://github.com/user-attachments/assets/dcf7fd60-d3cd-4789-b877-12aec7626c05)

**Comment by Luciferlocas** [comment]
Not only on the specific resume page, there is not back button on the card pages too. 

**Expectation:**

Add a back button on both the pages, so that the user can navigate back easily without having the need to use the browser navigation buttons.

@piyush-gangrade Assigning this issue to you.
