### ISSUE TITLE
Adding-my-resume

### ISSUE THREAD

**Issue by KAMAL-02** [Luciferlocas/nomen#52]
Hello, can i add my resume in it ?

**Comment by EuclidStellar** [comment]
sure Go ahead @KAMAL-02

**Comment by KAMAL-02** [comment]
> sure Go ahead @KAMAL-02

Hey, I just noticed we should avoid hardcoding the developers' locations. Instead, we can remove it since we already provide our location in the resume section
![image](https://github.com/user-attachments/assets/d94e942a-289d-4aad-9dec-2fa3617dc5e7)

**Comment by EuclidStellar** [comment]
Nice open a new issue for this I will assign you that issue @KAMAL-02

**Comment by KAMAL-02** [comment]
Okay!

**Comment by Ritesh381** [comment]
@EuclidStellar can I also add my resume
Please assign me this Or I can make a PR without assign
