### ISSUE TITLE
 Fix: Remove hardcoded developer locations

### ISSUE THREAD

**Issue by KAMAL-02** [Luciferlocas/nomen#59]
We currently have hardcoded developer locations in the Profile section. Since the developers location information is already provided in the resume section, we should remove these hardcoded values to avoid redundancy

Kindly assign it to me

**Comment by Luciferlocas** [comment]
Great job @KAMAL-02, I have been waiting for someone to notice it for a long time. 

Assigning the issue to @KAMAL-02

**Comment by KAMAL-02** [comment]
Thanks!
