### ISSUE TITLE
feat:  row division equally 

### ISSUE THREAD

**Issue by Luciferlocas** [Luciferlocas/nomen#76]
**Current:**

Both the rows are currently displaying the same card, one in the left and one in the right. Due to which to see some card a user have to wait for a long time.

**Expected:**

Divide the number of cards in equal part such that the first row displays the half number of card and the rest are being displayed by other.

**Guidance:** 

This can be done using the slice function, read about it and apply it there. You can refer to [MDN JavaScript slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice)

**Comment by Sarthak0419** [comment]
@Luciferlocas I would like to contribute to this issue.

**Comment by Luciferlocas** [comment]
Sure @Sarthak0419, assigning it to you.

**Comment by Vai-Man** [comment]
Can I also work on this?

**Comment by Vai-Man** [comment]
Can I also work on this? @Luciferlocas
