### ISSUE TITLE
issue : The speed of card is very fast , so it is not readable properly 

### ISSUE THREAD

**Issue by Atulgupta0403** [Luciferlocas/nomen#91]
Sir please assign this issue to me
![Screenshot 2024-10-20 170422](https://github.com/user-attachments/assets/0e3b8be6-b232-42b9-b431-54940876fe39)

**Comment by Luciferlocas** [comment]
I understand @Atulgupta0403, but the thing is, the speed of the card is changing due to browser and OS, in my linux I feel it slow and in my window I feel it fast. 

Thank you for noticing it, but this is not an code issue, so it can't be resolved.
